CREATE TABLE IF NOT EXISTS app_meta (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  meta_key VARCHAR(100) NOT NULL UNIQUE,
  meta_value VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
