CREATE TABLE IF NOT EXISTS call_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  provider_key VARCHAR(64) NOT NULL,
  provider_event_id VARCHAR(191) NOT NULL,
  provider_status VARCHAR(32) NOT NULL,
  call_outcome VARCHAR(32) NOT NULL,
  caller_number VARCHAR(32) NOT NULL,
  called_number VARCHAR(32) NOT NULL,
  occurred_at DATETIME NOT NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(32) NOT NULL DEFAULT 'RECORDED',
  disposition VARCHAR(64) NOT NULL DEFAULT 'no_action',
  lead_id BIGINT UNSIGNED NULL,
  patient_id BIGINT UNSIGNED NULL,
  message_id BIGINT UNSIGNED NULL,
  last_error VARCHAR(1000) NULL,
  raw_payload TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_call_events_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
  CONSTRAINT fk_call_events_lead FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE SET NULL,
  CONSTRAINT fk_call_events_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE SET NULL,
  CONSTRAINT fk_call_events_message FOREIGN KEY (message_id) REFERENCES communication_messages (id) ON DELETE SET NULL,
  UNIQUE KEY uq_call_events_provider_event (provider_key, provider_event_id),
  INDEX idx_call_events_org_time (organization_id, occurred_at),
  INDEX idx_call_events_lead (lead_id)
);
